"""Background code fixes — durable jobs, test gate, PR on green.

Pipeline: clone tenant repo → generate patches (Gemini / fixture deterministic)
→ apply in working tree → run tests → open multi-file PR. Never merges.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from loop.tenant import ConnectorReport, Tenant

_FILE_ALIASES: dict[str, list[str]] = {
    "payment/callback.ts": ["src/app/(store)/checkout/page.tsx", "src/lib/loop.ts"],
    "payment/3ds.ts": ["src/app/(store)/checkout/page.tsx"],
    "payment/authorization": ["src/app/(store)/checkout/page.tsx"],
}


def code_backend() -> str:
    return (os.environ.get("LOOP_CODE_BACKEND") or "auto").strip().lower()


def _token(tenant: Tenant | None = None) -> str:
    from loop.connectors.github import token_for_tenant

    return token_for_tenant(tenant)


def resolve_brief(action: Any, inv: Any, store: Any) -> dict[str, Any] | None:
    arts = dict(getattr(action, "artifacts", None) or {})
    raw = arts.get("code_brief")
    if isinstance(raw, dict) and raw.get("issue"):
        brief = dict(raw)
        if getattr(inv, "scenario_id", None):
            brief.setdefault("fixture_id", inv.scenario_id)
        return brief
    room_id = getattr(inv, "room_id", None)
    if room_id:
        for msg in store.list_messages(room_id):
            if msg.artifact_type == "code_brief" and isinstance(msg.artifact, dict):
                brief = dict(msg.artifact)
                if getattr(inv, "scenario_id", None):
                    brief.setdefault("fixture_id", inv.scenario_id)
                return brief
    return None


def _expand_files(paths: list[str], tenant: Tenant | None = None) -> list[str]:
    out: list[str] = []
    for p in paths:
        out.extend(_FILE_ALIASES.get(p, [p]))
    seen: set[str] = set()
    deduped: list[str] = []
    for p in out:
        if p not in seen:
            seen.add(p)
            deduped.append(p)
    if not deduped and tenant and tenant.code_paths:
        deduped = list(tenant.code_paths)
    return deduped


def clone_tenant_repo(tenant: Tenant, dest: Path) -> tuple[bool, str]:
    token = _token(tenant)
    if not token or not tenant.repo:
        return False, "no github token or tenant.repo"
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)
    dest.parent.mkdir(parents=True, exist_ok=True)
    url = f"https://x-access-token:{token}@github.com/{tenant.repo.strip()}.git"
    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", url, str(dest)],
            check=True,
            capture_output=True,
            text=True,
            timeout=180,
        )
        return True, str(dest)
    except (subprocess.CalledProcessError, subprocess.TimeoutError, OSError) as exc:
        detail = getattr(exc, "stderr", None) or str(exc)
        return False, f"clone failed: {str(detail)[:200]}"


def _read_repo_files(repo: Path, rel_paths: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for rel in rel_paths:
        path = repo / rel
        if path.is_file():
            out[rel] = path.read_text(encoding="utf-8", errors="replace")
    return out


def _deterministic_safari_patch(brief: dict[str, Any], files: dict[str, str]) -> dict[str, str]:
    """Fixture-only fallback for safari_3ds demo — not the default production path."""
    patches: dict[str, str] = dict(files)
    checkout = patches.get("src/app/(store)/checkout/page.tsx", "")
    if checkout and "2200" in checkout:
        patched = checkout.replace(
            "await new Promise((r) => setTimeout(r, 2200))",
            "// Product OS: Safari 3DS — fail fast instead of hanging shoppers\n"
            "      await new Promise((r) => setTimeout(r, 800))",
        )
        patches["src/app/(store)/checkout/page.tsx"] = patched

    loop_ts = patches.get("src/lib/loop.ts", "")
    if loop_ts and 'flags.pay_sdk === "4.3.0"' in loop_ts:
        patches["src/lib/loop.ts"] = loop_ts.replace(
            'return flags.pay_sdk_4_3 === "on" || flags.pay_sdk === "4.3.0"',
            "// Rollback path: only hang when explicitly forced (demo regression flag)\n"
            '  return flags.pay_sdk_4_3 === "on" && flags.pay_sdk !== "4.2.1"',
        )

    test_path = "tests/regression/safari-3ds-checkout.test.ts"
    if test_path not in patches:
        patches[test_path] = f"""/**
 * Regression: {brief.get("issue", "Safari 3DS checkout")}
 * Generated by Product OS Code Agent — human must review before merge.
 */
import {{ describe, it, expect }} from \"vitest\";
import {{ checkoutHung, sdkVersion }} from \"@/lib/loop\";

describe(\"Safari 3DS checkout regression\", () => {{
  it(\"SDK 4.2.1 rollback does not hang checkout\", () => {{
    const flags = {{ pay_sdk_4_3: \"off\", pay_sdk: \"4.2.1\" }};
    expect(sdkVersion(flags)).toBe(\"4.2.1\");
    expect(checkoutHung(flags)).toBe(false);
  }});
}});
"""
    return patches


def _parse_json_block(text: str) -> dict[str, Any]:
    text = text.strip()
    fence = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.S)
    if fence:
        text = fence.group(1)
    start, end = text.find("{"), text.rfind("}")
    if start >= 0 and end > start:
        text = text[start : end + 1]
    return json.loads(text)


def gemini_generate_patches(brief: dict[str, Any], files: dict[str, str]) -> tuple[dict[str, str], str]:
    from loop.model_armor import screen_chat, screen_model_response
    from loop.vertex_gemini import gemini_configured, generate_content_json, use_vertex

    if not gemini_configured():
        raise RuntimeError("Gemini not configured (set LOOP_USE_VERTEX=1 or GOOGLE_API_KEY)")

    target_paths = list(brief.get("likely_files") or list(files.keys()))
    screen_blob = json.dumps(
        {
            "task": "Suggest a minimal product code change as JSON.",
            "issue": str(brief.get("issue") or "")[:240],
            "hypothesis": str(brief.get("hypothesis") or "")[:240],
            "target_paths": target_paths,
        }
    )
    hit, needle, backend = screen_chat(screen_blob)
    if hit:
        raise RuntimeError(f"code-fix prompt blocked by Model Armor: {needle} ({backend})")

    prompt = {
        "task": "Return JSON with keys: files (path→full new file content), summary (string).",
        "issue": brief.get("issue"),
        "hypothesis": brief.get("hypothesis"),
        "expected_behavior": brief.get("expected_behavior"),
        "regression_test": brief.get("regression_test"),
        "target_paths": target_paths,
        "current_files": files,
        "rules": [
            "Make the smallest change that restores expected behavior.",
            "Prefer editing listed target paths.",
            "Add a regression test under tests/regression/ when reasonable.",
            "Keep existing Product OS ingest wiring intact.",
            "Return ONLY JSON.",
        ],
    }
    parsed = generate_content_json(json.dumps(prompt))
    text = json.dumps(parsed)
    hit_r, needle_r, backend_r = screen_model_response(str(text))
    if hit_r:
        raise RuntimeError(f"code-fix model response blocked by Model Armor: {needle_r} ({backend_r})")
    out_files = parsed.get("files") if isinstance(parsed.get("files"), dict) else {}
    merged = dict(files)
    for k, v in out_files.items():
        if isinstance(v, str) and v.strip():
            merged[str(k)] = v
    summary = str(parsed.get("summary") or ("Vertex patch" if use_vertex() else "Gemini patch"))
    if not any(merged.get(k) != files.get(k) for k in merged):
        raise RuntimeError("Gemini returned no file changes")
    return merged, summary


def generate_patches(repo: Path, brief: dict[str, Any], tenant: Tenant | None = None) -> tuple[dict[str, str], str, str]:
    rels = _expand_files(list(brief.get("likely_files") or []), tenant)
    existing = _read_repo_files(repo, rels)
    fixture = str(brief.get("fixture_id") or brief.get("scenario_id") or "")
    pref = code_backend()

    if fixture == "safari_3ds" or pref in {"deterministic", "fixture"}:
        patches = _deterministic_safari_patch(brief, existing)
        return patches, "safari fixture patch", "fixture"

    errors: list[str] = []

    if pref in {"antigravity", "auto"}:
        try:
            from loop.antigravity_fix import antigravity_generate_patches

            patches, summary = antigravity_generate_patches(repo, brief, existing)
            if patches:
                return patches, summary, "antigravity"
        except Exception as exc:
            errors.append(f"antigravity: {exc}")
            if pref == "antigravity":
                raise

    if pref in {"gemini", "auto", "antigravity"}:
        try:
            patches, summary = gemini_generate_patches(brief, existing)
            return patches, summary, "gemini"
        except Exception as exc:
            errors.append(f"gemini: {exc}")
            if pref == "gemini":
                raise

    if fixture == "safari_3ds":
        patches = _deterministic_safari_patch(brief, existing)
        return patches, f"safari fixture fallback ({'; '.join(errors)[:200]})", "fixture"

    raise RuntimeError(errors[-1] if errors else "no code backend available")


def open_flag_pr(
    tenant: Tenant,
    *,
    flags_doc: dict[str, str],
    title: str,
    body: str,
) -> ConnectorReport:
    """Open the tenant config/flags.json PR — required on HIGH approve."""
    from loop.connectors.github import open_pr
    from loop.tenant_context import flag_file_for

    content = json.dumps(flags_doc, indent=2) + "\n"
    return open_pr(
        tenant,
        title,
        body,
        file_path=flag_file_for(tenant),
        file_content=content,
    )


def run_code_fix(
    *,
    tenant: Tenant,
    brief: dict[str, Any],
    investigation_id: str,
    action_id: str,
    flag_patch: dict[str, str] | None = None,
    pr_title: str = "",
    pr_body: str = "",
    skip_flag_patch: bool = False,
) -> ConnectorReport:
    from loop.code_worker import (
        apply_patches,
        collect_git_diff_files,
        read_patched_files,
        run_tests,
    )
    from loop.connectors.github import open_pr_multi_file

    with tempfile.TemporaryDirectory(prefix="loop-code-") as tmp:
        repo = Path(tmp) / "repo"
        ok, detail = clone_tenant_repo(tenant, repo)
        if not ok:
            return ConnectorReport(status="skipped", connector="code_fix", detail=detail)

        patches, summary, backend = generate_patches(repo, brief, tenant)
        if flag_patch and not skip_flag_patch:
            from loop.tenant_context import flag_file_for

            patches[flag_file_for(tenant)] = json.dumps(flag_patch, indent=2) + "\n"

        touched = apply_patches(repo, patches)
        tests_ok, test_log = run_tests(repo, test_command=tenant.test_command or None)
        if not tests_ok:
            return ConnectorReport(
                status="failed",
                connector="code_fix",
                detail=f"tests failed — PR blocked: {test_log[:400]}",
            )

        pr_files = collect_git_diff_files(repo) or read_patched_files(repo, touched)
        if not pr_files:
            return ConnectorReport(status="failed", connector="code_fix", detail="no files to commit after patch")

        title = pr_title or f"Fix: {brief.get('issue', 'product regression')[:80]}"
        body = (
            (pr_body or "")
            + f"\n\n## Code Agent ({backend})\n{summary}\n\n"
            f"Tests: `{test_log[:200].strip()}`\n\n"
            f"Investigation `{investigation_id}` · action `{action_id}`.\n\n"
            "Product OS does not merge. Human review required."
        )
        return open_pr_multi_file(tenant, title, body, pr_files)


def run_code_fix_job(engine: Any, job: Any) -> dict[str, Any]:
    payload = job.payload or {}
    tenant = engine.store.get_tenant(str(payload.get("tenant_id") or ""))
    if not tenant:
        return {"status": "skipped", "detail": "no tenant bound to job"}

    inv = engine.store.get_investigation(str(payload.get("investigation_id") or ""))
    report = run_code_fix(
        tenant=tenant,
        brief=dict(payload.get("brief") or {}),
        investigation_id=str(payload.get("investigation_id") or ""),
        action_id=str(payload.get("action_id") or ""),
        flag_patch=dict(payload.get("flag_patch") or {}) or None,
        pr_title=str(payload.get("pr_title") or ""),
        pr_body=str(payload.get("pr_body") or ""),
        skip_flag_patch=bool(payload.get("flag_pr_opened")),
    )
    _apply_job_result(engine, payload, inv, report)
    return {
        "status": report.status,
        "detail": report.detail,
        "url": report.url,
        "connector": report.connector,
    }


def _post_code_fix_terminal_receipt(
    engine: Any,
    room_id: str,
    report: ConnectorReport,
    *,
    pr_url: str | None = None,
) -> None:
    from loop.proof import github_pr_proof
    from loop.receipts import post_receipt

    terminal = "failed" if report.status == "failed" else "done"
    title = "Code fix failed" if report.status == "failed" else "Code fix complete"
    if report.status == "skipped":
        title = "Code fix skipped"
    proof_url = str(report.url or pr_url or "")
    proof = github_pr_proof(proof_url, tenant=None) if proof_url and "github.com" in proof_url else None
    post_receipt(
        engine,
        room_id,
        kind="github" if proof else "code_fix",
        title=title,
        agent="code_agent",
        status=terminal,
        detail=report.detail,
        open_url=proof_url or None,
        proof=proof
        or {
            "kind": "code_fix",
            "status": terminal,
            "title": title,
            "detail": report.detail,
            "state": "open" if proof_url else "",
        },
    )


def _apply_job_result(engine: Any, payload: dict, inv: Any, report: ConnectorReport) -> None:
    from loop.world import post

    action_id = str(payload.get("action_id") or "")
    action = engine.store.get_action(action_id) if action_id else None
    tenant_id = str(payload.get("tenant_id") or "")
    tenant = engine.store.get_tenant(tenant_id) if tenant_id else None
    execution: dict[str, Any] = {}
    if action:
        execution = dict((action.artifacts or {}).get("execution") or {})
        had_pr = bool(execution.get("pr_opened") or execution.get("pr_url"))
        execution["code_fix"] = report.model_dump()
        if report.status == "applied" and report.url:
            if had_pr:
                execution["code_pr_url"] = report.url
            else:
                execution["pr_opened"] = True
                execution["pr_url"] = report.url
            if tenant:
                tenant.last_pr_url = str(report.url)
                tenant.last_connector = report.connector
                engine.store.put_tenant(tenant)
        elif report.status == "failed" and not had_pr:
            flag_patch = dict(payload.get("flag_patch") or {})
            pr_title = str(payload.get("pr_title") or "Product OS flag rollback")
            pr_body = str(payload.get("pr_body") or "")
            if tenant and tenant.repo and flag_patch:
                fallback = open_flag_pr(
                    tenant,
                    flags_doc=flag_patch,
                    title=pr_title,
                    body=pr_body or f"Investigation {payload.get('investigation_id') or ''}.",
                )
                execution["flag_pr_fallback"] = fallback.model_dump()
                if fallback.status == "applied" and fallback.url:
                    execution["pr_opened"] = True
                    execution["pr_url"] = fallback.url
                    execution["code_fix_failed"] = report.detail
                    if tenant:
                        tenant.last_pr_url = str(fallback.url)
                        tenant.last_connector = "github.pr flag fallback"
                        engine.store.put_tenant(tenant)
                else:
                    execution["pr_opened"] = False
                    execution["code_fix_failed"] = report.detail
            else:
                execution["pr_opened"] = False
                execution["code_fix_failed"] = report.detail
        elif report.status == "failed":
            execution["code_fix_failed"] = report.detail
        action.artifacts["execution"] = execution
        engine.store.put_action(action)
    room_id = getattr(inv, "room_id", None) if inv else None
    if room_id:
        if report.status == "applied" and report.url:
            from loop.live import HUB
            from loop.proof import github_pr_proof

            proof = github_pr_proof(str(report.url), tenant=tenant)
            post(
                engine,
                room_id,
                author="code_agent",
                author_kind="agent",
                kind="artifact",
                text=f"Opened PR: {report.url}",
                artifact_type="pr",
                artifact={
                    "pr_url": report.url,
                    "url": report.url,
                    "status": "open",
                    "detail": report.detail,
                    "proof": proof,
                },
            )
            room = engine.store.get_room(room_id)
            HUB.publish_global(
                {
                    "type": "payoff",
                    "kind": "pr_opened",
                    "room_id": room_id,
                    "pr_url": report.url,
                    "title": room.title if room else "",
                }
            )
        else:
            post(
                engine,
                room_id,
                author="code_agent",
                author_kind="agent",
                kind="artifact",
                text=report.detail,
                artifact_type="code_fix",
                artifact=report.model_dump(),
            )
        _post_code_fix_terminal_receipt(
            engine,
            room_id,
            report,
            pr_url=str(execution.get("pr_url") or "") or None,
        )
    if inv:
        engine.timeline(inv.id, "code_agent", "code_fix", report.detail, report.url or "")


def enqueue_code_fix_job(
    engine: Any,
    *,
    action_id: str,
    tenant: Tenant | None,
    inv: Any,
    brief: dict[str, Any],
    flag_patch: dict[str, str] | None,
    pr_title: str,
    pr_body: str,
    flag_pr_opened: bool = False,
) -> str | None:
    if not tenant:
        return None
    from loop.jobs import enqueue_code_fix

    job = enqueue_code_fix(
        engine.store,
        action_id=action_id,
        investigation_id=inv.id,
        tenant_id=tenant.id,
        brief=brief,
        flag_patch=flag_patch,
        pr_title=pr_title,
        pr_body=pr_body,
        flag_pr_opened=flag_pr_opened,
    )
    action = engine.store.get_action(action_id)
    if action:
        execution = dict((action.artifacts or {}).get("execution") or {})
        execution["job_id"] = job.id
        execution["code_fix"] = {"status": "queued", "job_id": job.id}
        action.artifacts["execution"] = execution
        engine.store.put_action(action)
    return job.id


# Back-compat alias used in tests
spawn_background_code_fix = enqueue_code_fix_job
