"""Agent Registry — identity, capabilities, permissions, risk. Not a prompt."""

from __future__ import annotations

from .models import RegistryEntry

# Governance answer: what stops engineering from reading customer data?
# Identity + Gateway allow-list. loop-code is denied customer_data / prod_db / gmail.send.

ENTRIES: list[RegistryEntry] = [
    RegistryEntry(
        id="signal_agent",
        display_name="Signal",
        owner="reliability@loop",
        capabilities=["detect_anomaly", "open_investigation", "classify_family"],
        permissions_allow=["warehouse.read", "ga4.read", "ads.read", "posthog.read"],
        permissions_deny=["gmail.send", "github.write", "prod.deploy", "customer_data.read"],
        version="2.4.1",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-analysis",
        room="pulse",
        role="Detects unusual behavior across technical, business, and customer signals",
        trust_boundary="TB-2",
    ),
    RegistryEntry(
        id="investigator_agent",
        display_name="Investigator",
        owner="reliability@loop",
        capabilities=["correlate", "dispatch_specialists", "independence_score"],
        permissions_allow=["warehouse.read", "logs.read", "deploys.read"],
        permissions_deny=["gmail.send", "github.write", "prod.deploy", "customer_data.read"],
        version="2.1.0",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-analysis",
        room="analysis",
        role="Correlates analytics, logs, deployments, and errors",
        trust_boundary="TB-2",
    ),
    RegistryEntry(
        id="analytics_agent",
        display_name="Analytics",
        owner="data@loop",
        capabilities=["funnel_facts", "segment_breakdown", "bigquery.read"],
        permissions_allow=["ga4.read", "bigquery.read", "posthog.read", "firebase.read"],
        permissions_deny=["gmail.send", "github.write", "prod.deploy"],
        version="2.3.0",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-analysis",
        room="analysis",
        role="Funnel / segment facts from daily tables — never raw rows into Memory Bank",
        trust_boundary="TB-2",
    ),
    RegistryEntry(
        id="logs_agent",
        display_name="Logs",
        owner="sre@loop",
        capabilities=["error_signatures", "cloud_logging.read"],
        permissions_allow=["logs.read"],
        permissions_deny=["gmail.send", "github.write", "prod.deploy", "customer_data.read"],
        version="2.2.0",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-analysis",
        room="analysis",
        role="Error signatures vs deploy window",
        trust_boundary="TB-2",
    ),
    RegistryEntry(
        id="deployment_agent",
        display_name="Deployment",
        owner="sre@loop",
        capabilities=["release_timeline", "correlate_onset"],
        permissions_allow=["deploys.read", "github.read"],
        permissions_deny=["github.write", "prod.deploy", "gmail.send"],
        version="2.0.4",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-analysis",
        room="analysis",
        role="Release timeline correlation",
        trust_boundary="TB-2",
    ),
    RegistryEntry(
        id="database_agent",
        display_name="Database",
        owner="data@loop",
        capabilities=["warehouse_aggregate"],
        permissions_allow=["warehouse.read"],
        permissions_deny=["prod.db.write", "customer_data.export"],
        version="1.9.0",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-analysis",
        room="analysis",
        role="Warehouse aggregates only — never a production primary",
        trust_boundary="TB-2",
    ),
    RegistryEntry(
        id="customer_voice_agent",
        display_name="Customer Voice",
        owner="research@loop",
        capabilities=["diagnostic_call", "structured_evidence", "live_fallback"],
        permissions_allow=["media_bridge.session", "sdp.redact"],
        permissions_deny=["prod.db.read", "customer_records.dump", "gmail.send"],
        version="2.6.0",
        environment="prod",
        risk_level="HIGH",
        status="active",
        identity="loop-customer",
        room="voice",
        role="Adaptive diagnostic calls with context; structured JSON, never a transcript dump",
        trust_boundary="TB-3",
    ),
    RegistryEntry(
        id="customer_simulator",
        display_name="Customer Simulator",
        owner="eval@loop",
        capabilities=["persona_confused", "persona_angry", "persona_technical"],
        permissions_allow=["eval.simulate"],
        permissions_deny=["prod.db.read", "gmail.send", "github.write"],
        version="1.4.0",
        environment="eval",
        risk_level="LOW",
        status="active",
        identity="loop-customer",
        room="voice",
        role="Confused / angry / technical customers for voice eval",
        trust_boundary="TB-3",
    ),
    RegistryEntry(
        id="feedback_agent",
        display_name="Feedback",
        owner="research@loop",
        capabilities=["extract_reasons", "cluster_requests"],
        permissions_allow=["memory.customer.write", "warehouse.read"],
        permissions_deny=["gmail.send", "github.write"],
        version="2.1.2",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-orchestration",
        room="voice",
        role="Extracts structured reasons; clusters feature requests",
        trust_boundary="TB-1",
    ),
    RegistryEntry(
        id="evidence_agent",
        display_name="Evidence",
        owner="reliability@loop",
        capabilities=["aggregate_packs", "independence_groups"],
        permissions_allow=["warehouse.read", "logs.read", "memory.read"],
        permissions_deny=["gmail.send", "prod.deploy"],
        version="2.0.1",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-orchestration",
        room="command",
        role="Aggregates customer + analytics + logs + deploy + segmentation",
        trust_boundary="TB-1",
    ),
    RegistryEntry(
        id="root_cause_agent",
        display_name="Root Cause",
        owner="reliability@loop",
        capabilities=["hypothesis", "three_source_gate"],
        permissions_allow=["memory.read"],
        permissions_deny=["github.write", "prod.deploy", "gmail.send"],
        version="2.5.0",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-orchestration",
        room="command",
        role="Likely bug/config/product cause with confidence and evidence checklist",
        trust_boundary="TB-1",
    ),
    RegistryEntry(
        id="risk_agent",
        display_name="Risk",
        owner="security@loop",
        capabilities=["tier_surface", "approval_gate"],
        permissions_allow=["policy.read"],
        permissions_deny=["prod.deploy", "customer_data.read"],
        version="3.0.0",
        environment="prod",
        risk_level="HIGH",
        status="active",
        identity="loop-orchestration",
        room="command",
        role="LOW auto / MEDIUM developer / HIGH mandatory human — surface, not model confidence",
        trust_boundary="TB-1",
    ),
    RegistryEntry(
        id="code_agent",
        display_name="Code",
        owner="eng@loop",
        capabilities=["investigate_repo", "open_pr", "security_check"],
        permissions_allow=["github.read", "github.write", "ci.read"],
        permissions_deny=["gmail.send", "prod.deploy", "customer_data.read", "prod.db.read"],
        version="2.8.0",
        environment="prod",
        risk_level="HIGH",
        status="active",
        identity="loop-code",
        room="code",
        role="Antigravity + GitHub: plan, patch, tests, PR — never merge, never customer records",
        trust_boundary="TB-4",
    ),
    RegistryEntry(
        id="test_agent",
        display_name="Test",
        owner="eng@loop",
        capabilities=["generate_regression", "run_sandbox"],
        permissions_allow=["github.read", "ci.write"],
        permissions_deny=["prod.deploy", "customer_data.read"],
        version="1.7.0",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-code",
        room="code",
        role="Regression must fail pre-change and pass post-change",
        trust_boundary="TB-4",
    ),
    RegistryEntry(
        id="product_agent",
        display_name="Product",
        owner="pm@loop",
        capabilities=["impact_estimate", "prd", "github_issue"],
        permissions_allow=["warehouse.read", "github.issues.write", "docs.draft"],
        permissions_deny=["prod.deploy", "github.merge", "customer_data.export"],
        version="2.2.3",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-product",
        room="product",
        role="Feature requests with frequency, revenue, churn, competitor, estimate",
        trust_boundary="TB-5",
    ),
    RegistryEntry(
        id="experiment_agent",
        display_name="Experiment",
        owner="growth@loop",
        capabilities=["design", "pct_rollout", "guardrails"],
        permissions_allow=["flags.write", "metrics.read"],
        permissions_deny=["prod.deploy", "gmail.send"],
        version="2.0.0",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-experiment",
        room="product",
        role="Hypothesis → design → ship to % → monitor control/treatment",
        trust_boundary="TB-6",
    ),
    RegistryEntry(
        id="learning_agent",
        display_name="Learning",
        owner="reliability@loop",
        capabilities=["verify_outcome", "write_lesson"],
        permissions_allow=["metrics.read", "memory.write"],
        permissions_deny=["github.write", "prod.deploy"],
        version="2.1.0",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-learning",
        room="memory",
        role="Post-fix/post-ship: compare metrics, store the lesson",
        trust_boundary="TB-7",
    ),
    RegistryEntry(
        id="security_policy_agent",
        display_name="Security / Policy",
        owner="security@loop",
        capabilities=["identity_check", "gateway_enforce", "model_armor"],
        permissions_allow=["policy.enforce", "audit.write"],
        permissions_deny=["customer_records.dump", "prod.db.export"],
        version="3.1.0",
        environment="prod",
        risk_level="HIGH",
        status="active",
        identity="loop-security",
        room="command",
        role="Identity → permission → gateway → allow/deny/human. Never comply with exfil.",
        trust_boundary="TB-0",
    ),
    RegistryEntry(
        id="coordination_agent",
        display_name="Developer Coordination",
        owner="eng-manager@loop",
        capabilities=["codeowners", "calendar_slot", "meet_draft", "gmail_draft"],
        permissions_allow=["calendar.read", "gmail.draft", "chat.notify"],
        permissions_deny=["gmail.send", "prod.deploy"],
        version="1.5.0",
        environment="prod",
        risk_level="LOW",
        status="active",
        identity="loop-product",
        room="ops",
        role="CODEOWNER, Calendar availability, estimate review, Meet + Gmail draft (never send)",
        trust_boundary="TB-5",
    ),
    RegistryEntry(
        id="orchestrator",
        display_name="Incident Commander",
        owner="reliability@loop",
        capabilities=["discover_registry", "a2a_coordinate", "lifecycle"],
        permissions_allow=["registry.read", "a2a.invoke"],
        permissions_deny=["gather_evidence", "prod.deploy", "customer_data.read"],
        version="2.9.0",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-orchestration",
        room="command",
        role="Discovers agents via Registry; coordinates via A2A; never gathers itself",
        trust_boundary="TB-1",
    ),
    RegistryEntry(
        id="product_intelligence_agent",
        display_name="Product Intelligence",
        owner="research@loop",
        capabilities=["universal_search", "gmail.search", "drive.search", "calendar.search"],
        permissions_allow=["workspace.search.user_oauth"],
        permissions_deny=["workspace.send", "customer_records.dump"],
        version="1.2.0",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-product",
        room="research",
        role="Universal Search across Gmail, Drive, Calendar, Chat when user OAuth is present",
        trust_boundary="TB-5",
    ),
    RegistryEntry(
        id="consent_agent",
        display_name="Consent",
        owner="privacy@loop",
        capabilities=["consent_gate", "frequency_cap"],
        permissions_allow=["consent.read"],
        permissions_deny=["outreach.unconsented"],
        version="1.3.0",
        environment="prod",
        risk_level="HIGH",
        status="active",
        identity="loop-customer",
        room="voice",
        role="Hard-gate outreach: consent, frequency cap, jurisdiction",
        trust_boundary="TB-3",
    ),
    RegistryEntry(
        id="decision_agent",
        display_name="Decision",
        owner="reliability@loop",
        capabilities=["adjudicate"],
        permissions_allow=["memory.read"],
        permissions_deny=["prod.deploy"],
        version="1.1.0",
        environment="prod",
        risk_level="MEDIUM",
        status="active",
        identity="loop-orchestration",
        room="command",
        role="Adjudicate competing hypotheses with attached evidence only",
        trust_boundary="TB-1",
    ),
]


def by_id() -> dict[str, RegistryEntry]:
    return {e.id: e for e in ENTRIES}


def gateway_allows(agent_id: str, permission: str) -> bool:
    entry = by_id().get(agent_id)
    if not entry:
        return False
    if permission in entry.permissions_deny:
        return False
    return permission in entry.permissions_allow


def identity_for(agent_id: str) -> str:
    entry = by_id().get(agent_id)
    return entry.identity if entry else "unknown"
