import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f5f5f7",
        foreground: "#1d1d1f",
        card: "#ffffff",
        muted: "#f5f5f7",
        border: "#e5e5ea",
        accent: "#0071e3",
        copper: "#0077ed",
        danger: "#de3b2f",
        warn: "#b75106",
        ok: "#248a3d",
        /* ProductOps reference tokens (ui/stitch_autonomous_product_operations_os) */
        "on-surface": "#1b1b1d",
        "on-surface-variant": "#45464d",
        "on-background": "#1b1b1d",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f5",
        "surface-container": "#f0edef",
        "surface-container-high": "#eae7e9",
        "surface-variant": "#e4e2e4",
        "outline-variant": "#c6c6cd",
        outline: "#76777d",
        secondary: "#4648d4",
        "secondary-container": "#6063ee",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "inverse-primary": "#bec6e0",
        "inverse-surface": "#303032",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "text-primary": "#1d1d1f",
        "text-secondary": "#86868b",
        "surface-subtle": "#e5e5ea",
        "surface-base": "#f5f5f7",
        "surface-bright": "#fcf8fa",
        "accent-success": "#34c759",
        "accent-warning": "#f59e0b",
        "primary-container": "#131b2e",
      },
      spacing: {
        gutter: "16px",
        "container-padding": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-md": "24px",
        "margin-lg": "40px",
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "body-md": ["14px", { lineHeight: "20px" }],
        "body-sm": ["12px", { lineHeight: "16px" }],
        "code-sm": ["12px", { lineHeight: "18px" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "IBM Plex Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "0.875rem",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      boxShadow: {
        soft: "0 1px 2px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.04)",
        card: "0 1px 3px rgba(0,0,0,0.05), 0 4px 12px rgba(0,0,0,0.04)",
      },
      transitionTimingFunction: {
        out: "cubic-bezier(0.22, 1, 0.36, 1)",
        spring: "cubic-bezier(0.34, 1.28, 0.64, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
